insert into hw6.product (name, cost) values ('Vodka - Smirnoff', 12.237);
insert into hw6.product (name, cost) values ('Lamb - Rack', 25.145);
insert into hw6.product (name, cost) values ('Oil - Canola', 99.406);
insert into hw6.product (name, cost) values ('Wine - Trimbach Pinot Blanc', 19.962);
insert into hw6.product (name, cost) values ('Celery Root', 48.447);
insert into hw6.product (name, cost) values ('Lemon Balm - Fresh', 75.357);
insert into hw6.product (name, cost) values ('Wine - Zinfandel California 2002', 75.384);
insert into hw6.product (name, cost) values ('Shrimp - Baby, Warm Water', 81.282);
insert into hw6.product (name, cost) values ('Wine - Malbec Trapiche Reserve', 43.229);
insert into hw6.product (name, cost) values ('Salmon - Sockeye Raw', 2.768);
insert into hw6.product (name, cost) values ('Lobster - Baby, Boiled', 75.969);
insert into hw6.product (name, cost) values ('Coconut - Creamed, Pure', 99.803);
insert into hw6.product (name, cost) values ('Pork - Ham Hocks - Smoked', 83.333);
insert into hw6.product (name, cost) values ('Goulash Seasoning', 31.248);
insert into hw6.product (name, cost) values ('Wine - Cave Springs Dry Riesling', 75.506);
insert into hw6.product (name, cost) values ('Soup Campbells Mexicali Tortilla', 27.81);
insert into hw6.product (name, cost) values ('Beef - Ground, Extra Lean, Fresh', 87.012);
insert into hw6.product (name, cost) values ('Beer - Blue Light', 8.879);
insert into hw6.product (name, cost) values ('Dish Towel', 57.493);
insert into hw6.product (name, cost) values ('Potatoes - Mini White 3 Oz', 92.359);
insert into hw6.product (name, cost) values ('Beer - Fruli', 22.574);
insert into hw6.product (name, cost) values ('Chips - Potato Jalapeno', 10.382);
insert into hw6.product (name, cost) values ('Cake - Lemon Chiffon', 69.694);
insert into hw6.product (name, cost) values ('Energy Drink - Redbull 355ml', 68.578);
insert into hw6.product (name, cost) values ('Chicken - Bones', 25.554);
insert into hw6.product (name, cost) values ('Bread - Bistro White', 40.602);
insert into hw6.product (name, cost) values ('Juice - V8, Tomato', 75.634);
insert into hw6.product (name, cost) values ('Cranberries - Fresh', 41.756);
insert into hw6.product (name, cost) values ('Eggplant - Asian', 80.584);
insert into hw6.product (name, cost) values ('Appetizer - Assorted Box', 27.353);
insert into hw6.product (name, cost) values ('Sugar - Palm', 12.747);
insert into hw6.product (name, cost) values ('Duck - Fat', 19.123);
insert into hw6.product (name, cost) values ('Cookie Double Choco', 93.587);
insert into hw6.product (name, cost) values ('Sauce - Thousand Island', 58.404);
insert into hw6.product (name, cost) values ('Flower - Dish Garden', 50.046);
insert into hw6.product (name, cost) values ('Soup - Campbells Tomato Ravioli', 94.818);
insert into hw6.product (name, cost) values ('Pepper - Orange', 60.838);
insert into hw6.product (name, cost) values ('Tart - Pecan Butter Squares', 73.298);
insert into hw6.product (name, cost) values ('Cookie - Dough Variety', 67.392);
insert into hw6.product (name, cost) values ('Tea - Herbal Sweet Dreams', 83.313);
insert into hw6.product (name, cost) values ('Silicone Parch. 16.3x24.3', 54.301);
insert into hw6.product (name, cost) values ('Lid - Translucent, 3.5 And 6 Oz', 60.0);
insert into hw6.product (name, cost) values ('Pimento - Canned', 90.028);
insert into hw6.product (name, cost) values ('Oats Large Flake', 5.961);
insert into hw6.product (name, cost) values ('Honey - Comb', 47.226);
insert into hw6.product (name, cost) values ('Cheese - Swiss Sliced', 54.949);
insert into hw6.product (name, cost) values ('Puree - Strawberry', 34.875);
insert into hw6.product (name, cost) values ('Wine - Semi Dry Riesling Vineland', 51.597);
insert into hw6.product (name, cost) values ('Wine - Sicilia Igt Nero Avola', 4.979);
insert into hw6.product (name, cost) values ('Aspic - Light', 61.661);
insert into hw6.product (name, cost) values ('Mortadella', 43.818);
insert into hw6.product (name, cost) values ('Muffin Mix - Oatmeal', 21.305);
insert into hw6.product (name, cost) values ('Grapefruit - White', 49.626);
insert into hw6.product (name, cost) values ('Bread - Roll, Canadian Dinner', 74.205);
insert into hw6.product (name, cost) values ('Sage Ground Wiberg', 66.62);
insert into hw6.product (name, cost) values ('Cookies - Oreo, 4 Pack', 92.323);
insert into hw6.product (name, cost) values ('Chocolate - Sugar Free Semi Choc', 4.224);
insert into hw6.product (name, cost) values ('Dc - Sakura Fu', 75.394);
insert into hw6.product (name, cost) values ('Plate Foam Laminated 9in Blk', 52.196);
insert into hw6.product (name, cost) values ('Veal - Round, Eye Of', 4.634);
insert into hw6.product (name, cost) values ('Pork - Smoked Back Bacon', 70.746);
insert into hw6.product (name, cost) values ('Lid - 10,12,16 Oz', 37.999);
insert into hw6.product (name, cost) values ('Wasabi Paste', 84.104);
insert into hw6.product (name, cost) values ('Pasta - Lasagna, Dry', 39.8);
insert into hw6.product (name, cost) values ('Muffin Mix - Chocolate Chip', 54.73);
insert into hw6.product (name, cost) values ('Sugar - Invert', 87.322);
insert into hw6.product (name, cost) values ('Blackberries', 61.238);
insert into hw6.product (name, cost) values ('Soup - Knorr, Chicken Noodle', 41.726);
insert into hw6.product (name, cost) values ('Flower - Carnations', 52.486);
insert into hw6.product (name, cost) values ('Pastry - Cherry Danish - Mini', 35.587);
insert into hw6.product (name, cost) values ('Tomato - Green', 62.189);
insert into hw6.product (name, cost) values ('Wine - Stoneliegh Sauvignon', 29.531);
insert into hw6.product (name, cost) values ('Cookie Dough - Double', 57.818);
insert into hw6.product (name, cost) values ('Ice Cream - Turtles Stick Bar', 20.654);
insert into hw6.product (name, cost) values ('Nantucket - Carrot Orange', 2.478);
insert into hw6.product (name, cost) values ('Syrup - Kahlua Chocolate', 74.48);
insert into hw6.product (name, cost) values ('Chocolate Liqueur - Godet White', 84.441);
insert into hw6.product (name, cost) values ('Instant Coffee', 35.594);
insert into hw6.product (name, cost) values ('Bread - Roll, Soft White Round', 46.098);
insert into hw6.product (name, cost) values ('Dehydrated Kelp Kombo', 11.123);
insert into hw6.product (name, cost) values ('Carbonated Water - Cherry', 44.431);
insert into hw6.product (name, cost) values ('Smirnoff Green Apple Twist', 44.108);
insert into hw6.product (name, cost) values ('Nori Sea Weed', 67.618);
insert into hw6.product (name, cost) values ('Wine - Red, Wolf Blass, Yellow', 1.429);
insert into hw6.product (name, cost) values ('Dill Weed - Fresh', 68.586);
insert into hw6.product (name, cost) values ('Steam Pan - Half Size Deep', 19.68);
insert into hw6.product (name, cost) values ('Wine - Pinot Noir Latour', 42.668);
insert into hw6.product (name, cost) values ('Flower - Commercial Spider', 32.041);
insert into hw6.product (name, cost) values ('Muffin Puck Ww Carrot', 86.544);
insert into hw6.product (name, cost) values ('Lettuce Romaine Chopped', 82.179);
insert into hw6.product (name, cost) values ('Capon - Breast, Double, Wing On', 81.313);
insert into hw6.product (name, cost) values ('Longos - Grilled Salmon With Bbq', 96.47);
insert into hw6.product (name, cost) values ('Beans - French', 71.357);
insert into hw6.product (name, cost) values ('Food Colouring - Pink', 61.696);
insert into hw6.product (name, cost) values ('Cookies - Fortune', 1.18);
insert into hw6.product (name, cost) values ('Beer - Mcauslan Apricot', 43.04);
insert into hw6.product (name, cost) values ('Tomatoes - Vine Ripe, Yellow', 87.103);
insert into hw6.product (name, cost) values ('Turkey - Oven Roast Breast', 20.2);
insert into hw6.product (name, cost) values ('Crab - Blue, Frozen', 26.031);



insert into hw6.customer (name) values ('Pam');
insert into hw6.customer (name) values ('Joelly');
insert into hw6.customer (name) values ('Gilda');
insert into hw6.customer (name) values ('Gonzalo');
insert into hw6.customer (name) values ('Yurik');
insert into hw6.customer (name) values ('Ilise');
insert into hw6.customer (name) values ('Blanch');
insert into hw6.customer (name) values ('Cory');
insert into hw6.customer (name) values ('Stacee');
insert into hw6.customer (name) values ('Roth');
insert into hw6.customer (name) values ('Mame');
insert into hw6.customer (name) values ('Scott');
insert into hw6.customer (name) values ('Brok');
insert into hw6.customer (name) values ('Allie');
insert into hw6.customer (name) values ('Farrah');
insert into hw6.customer (name) values ('Jasmin');
insert into hw6.customer (name) values ('Pierrette');
insert into hw6.customer (name) values ('Ilsa');
insert into hw6.customer (name) values ('Annamarie');
insert into hw6.customer (name) values ('Stillmann');
insert into hw6.customer (name) values ('Flinn');
insert into hw6.customer (name) values ('Dicky');
insert into hw6.customer (name) values ('Miller');
insert into hw6.customer (name) values ('Orelee');
insert into hw6.customer (name) values ('Ortensia');
insert into hw6.customer (name) values ('Mel');
insert into hw6.customer (name) values ('Rickie');
insert into hw6.customer (name) values ('Kris');
insert into hw6.customer (name) values ('Donelle');
insert into hw6.customer (name) values ('Torrence');
insert into hw6.customer (name) values ('Palm');
insert into hw6.customer (name) values ('Lilah');
insert into hw6.customer (name) values ('Dallas');
insert into hw6.customer (name) values ('Ingra');
insert into hw6.customer (name) values ('Dimitri');
insert into hw6.customer (name) values ('Leighton');
insert into hw6.customer (name) values ('Simmonds');
insert into hw6.customer (name) values ('Mozes');
insert into hw6.customer (name) values ('Hayley');
insert into hw6.customer (name) values ('Lonnie');
insert into hw6.customer (name) values ('Alia');
insert into hw6.customer (name) values ('Ardine');
insert into hw6.customer (name) values ('Roxie');
insert into hw6.customer (name) values ('Kania');
insert into hw6.customer (name) values ('Mela');
insert into hw6.customer (name) values ('Georgine');
insert into hw6.customer (name) values ('Fritz');
insert into hw6.customer (name) values ('Sharyl');
insert into hw6.customer (name) values ('Noland');
insert into hw6.customer (name) values ('Millisent');
insert into hw6.customer (name) values ('Teri');
insert into hw6.customer (name) values ('Fair');
insert into hw6.customer (name) values ('Bekki');
insert into hw6.customer (name) values ('Griffin');
insert into hw6.customer (name) values ('Lane');
insert into hw6.customer (name) values ('Barnaby');
insert into hw6.customer (name) values ('Kissee');
insert into hw6.customer (name) values ('Papageno');
insert into hw6.customer (name) values ('Forster');
insert into hw6.customer (name) values ('Marys');
insert into hw6.customer (name) values ('Calhoun');
insert into hw6.customer (name) values ('See');
insert into hw6.customer (name) values ('Laryssa');
insert into hw6.customer (name) values ('Artemas');
insert into hw6.customer (name) values ('Saree');
insert into hw6.customer (name) values ('Gearard');
insert into hw6.customer (name) values ('Luis');
insert into hw6.customer (name) values ('Rebekah');
insert into hw6.customer (name) values ('Durant');
insert into hw6.customer (name) values ('Vonnie');
insert into hw6.customer (name) values ('Daffi');
insert into hw6.customer (name) values ('Kathy');
insert into hw6.customer (name) values ('Merralee');
insert into hw6.customer (name) values ('Ozzie');
insert into hw6.customer (name) values ('Lazar');
insert into hw6.customer (name) values ('Ethelind');
insert into hw6.customer (name) values ('Giorgi');
insert into hw6.customer (name) values ('Tome');
insert into hw6.customer (name) values ('Bernardine');
insert into hw6.customer (name) values ('Brett');
insert into hw6.customer (name) values ('Gard');
insert into hw6.customer (name) values ('Fletcher');
insert into hw6.customer (name) values ('Gisele');
insert into hw6.customer (name) values ('Daile');
insert into hw6.customer (name) values ('Edd');
insert into hw6.customer (name) values ('Emory');
insert into hw6.customer (name) values ('Aylmar');
insert into hw6.customer (name) values ('Fabien');
insert into hw6.customer (name) values ('Hernando');
insert into hw6.customer (name) values ('Aubert');
insert into hw6.customer (name) values ('Linet');
insert into hw6.customer (name) values ('Bunny');
insert into hw6.customer (name) values ('Leoline');
insert into hw6.customer (name) values ('Devlen');
insert into hw6.customer (name) values ('Biddie');
insert into hw6.customer (name) values ('Siward');
insert into hw6.customer (name) values ('Farra');
insert into hw6.customer (name) values ('Ginni');
insert into hw6.customer (name) values ('Laurene');
insert into hw6.customer (name) values ('Packston');